### ISSUE TITLE
Repeat-Cycle vs. Cron job

### ISSUE THREAD

**Issue by KarstenDE** [c5te1n/node-red-contrib-dwd-local-weather#10]
I understood, the the weather forecast gets published around minute 25 (:25) every hour.
Therefore I would be happy the node load the data always around minute 30 (:30) every hour. I tried to use a cron node to initiate the flow every hour at the configured time. Then I configured the repeat-cycle to `0`  
But the weather forecast is not fetched by this config.

Long story short: is it possible to control the execution of this weather node more exactly?

Thanks!

**Comment by c5te1n** [comment]
This is for the MOSMIX S data file and I thought about syncing the updates with the publishing cycle of DWD while implementing the node. The problem is that the node is using the MOSMIX L data file right now because only this file is broken down by station and with that we don't have to download the full dump of ALL stations once per hour. However, the MOSMIX L files are updated only 4 times a day - so syncing with that does not add much to the accuracy vs. just downloading it once per hour as we do now.

See: https://www.dwd.de/DE/leistungen/met_verfahren_mosmix/met_verfahren_mosmix.html
